### ISSUE TITLE
what is music player called.

### ISSUE THREAD

**Issue by mrlinuxdude** [Tail-R/xmonad_eww_dotfiles#2]
trying to find music player under eww. what is it. Thanks for amazing work

**Comment by Tail-R** [comment]
i using plyerctl command insted. you can see the script at the new_eww/scripts/mpris.sh. the playerctl can retrieve the music infomation from spotify, firefox, etc... using mpris protocol ! this is my favorite command.

**Comment by Tail-R** [comment]
if your using firefox. play some youtube video and check the $HOME/.mozilla/firefox/firefox-mpris directory. i think you can find a little thumbnail in the directory. the playerctl return that path
